shop/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as userViews
from django.contrib.auth import views as authViews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('registration/', userViews.register, name="reg"),
    path('login/', authViews.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('exit/', authViews.LogoutView.as_view(template_name='web/index.html'), name="exit"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('shop/', views.shop, name='shop'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/<int:id>', views.delete_from_cart, name='delete_from_cart'),
    path('pay/<int:id>', views.pay, name='pay'),
    path('comments/', views.cart, name='comments'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Comments(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор комментария')
    text = models.TextField(verbose_name='Текст комментария', max_length=255)

web/templates/web/cart.html
{% extends 'web/main.html' %}
{% load static %}
{% block title_page %}
    <title>Магазин</title>

{% endblock title_page %}
{% block content %}
    {% if user.is_authenticated %}
        <div style="position: absolute; right: 50%; transform: translateX(50%); margin-top: 30px;">
            <a href="window.location.href = {% url 'reg' %}" type="submit" class="btn btn-light">Профиль</a>
            <a onclick="window.location.href = {% url 'exit' %}" type="submit" class="btn btn-light">Выход</a>
        </div>
    {% else %}
        <div style="position: absolute; right: 50%; transform: translateX(50%); margin-top: 30px;">
            <button onclick="window.location.href = {% url 'reg' %}" type="submit" class="btn btn-light">Регистрация
            </button>
            <button onclick="window.location.href = {% url 'login' %}" type="submit" class="btn btn-outline-info">Вход
            </button>
        </div>
    {% endif %}
    <section class="main-section paddind" id="Portfolio" style="
  background: #eecda3;
  background: -webkit-linear-gradient(to right, #eecda3, #62efa1);
  background: linear-gradient(to right, #eecda3, #60d092);
  min-height: 100vh;

">
        <div class="px-4 px-lg-0">
            <!-- For demo purpose -->
            <div class="container text-white text-center">
                <h1 class="display-4">Корзина</h1>
                </p>
            </div>
            <!-- End -->

            <div class="pb-5">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">

                            <!-- Shopping cart table -->
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="p-2 px-3 text-uppercase">Товар</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Цена</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Количество</div>
                                        </th>

                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Удалить</div>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for cart_entry in cart.cartentry_set.all %}
                                        {% if cart_entry.product.availability %}
                                            <tr>
                                                <th scope="row" class="border-0">
                                                    <div class="p-2">
                                                        <img src="{{ cart_entry.product.img.url }}"
                                                             alt="" width="70" class="img-fluid rounded shadow-sm">
                                                        <div class="ml-3 d-inline-block align-middle">
                                                            <h5 class="mb-0"><a href="#"
                                                                                class="text-dark d-inline-block align-middle">{{ cart_entry.product.name }}</a>
                                                            </h5><span
                                                                class="text-muted font-weight-normal font-italic d-block">Категория: {{ cart_entry.product.group }}</span>
                                                        </div>
                                                    </div>
                                                </th>
                                                <td class="border-0 align-middle"><strong>{{ cart_entry.product.price }} ₽</strong>
                                                <td class="border-0 align-middle"><strong>{{ cart_entry.count }}</strong>
                                                </td>
                                                <form id="delete_form_{{ cart_entry.product.pk }}" method="post"
                                                      action="{% url 'delete_from_cart' cart_entry.product.pk %}">
                                                    {% csrf_token %}
                                                    <script>
                                                        function perform_delete_{{ cart_entry.product.pk }}() {
                                                            document.forms.delete_form_{{ cart_entry.product.pk }}.submit()
                                                        }
                                                    </script>
                                                    <td class="border-0 align-middle">
                                                        <a href="#" onclick="perform_delete_{{ cart_entry.product.pk }}()"
                                                           class="text-dark">
                                                            <i class="fa fa-trash"></i>
                                                        </a>
                                                    </td>
                                                </form>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- End -->
                        </div>
                    </div>

                    <form method="post" action="{% url 'pay' cart.pk %}">
                        {% csrf_token %}
                        <div class="row py-5 p-4 bg-white rounded shadow-sm">
                            <div class="col-lg-6">
                                <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Данные
                                    заказчика
                                </div>
                                <div class="p-4">
                                    <form>
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="exampleInputEmail1"
                                                   aria-describedby="emailHelp" placeholder="Введите ФИО"
                                                   name="fullName">
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="exampleInputPassword1"
                                                   placeholder="Ваш номер" name="number">
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="exampleInputPassword1"
                                                   placeholder="Ваш адресс" name="address">
                                        </div>
                                        <div class="form-group">
                                            <select type="text" class="form-control" id="exampleInputPassword1"
                                                    name="pay">
                                                <option value="0" disabled selected>Выберите способ оплаты</option>
                                                <option value="0">Налиными</option>
                                                <option value="1">Онлайн картой</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <select type="text" class="form-control" id="deliveryInput"
                                                    name="delivery">
                                                <option value="0" disabled selected>Выберите способ доставки</option>
                                                <option value="0">Самовывоз</option>
                                                <option value="250">Доставка (₽250.00)</option>
                                            </select>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Итог заказа
                                </div>
                                <div class="p-4">
                                    <p class="font-italic mb-4">Доставка и дополнительные расходы рассчитываются на
                                        основе
                                        значений, которые вы ввели.</p>
                                    <ul class="list-unstyled mb-4">
                                        <li class="d-flex justify-content-between py-3 border-bottom"><strong
                                                class="text-muted">Сумма
                                            товаров </strong><strong id="price">₽{{ price }}.00</strong></li>
                                        <li class="d-flex justify-content-between py-3 border-bottom"
                                            id="delivery-output"><strong
                                                class="text-muted">Доставка</strong><strong>₽250.00</strong></li>
                                        <li class="d-flex justify-content-between py-3 border-bottom"><strong
                                                class="text-muted">Общая сумма</strong>
                                            <h5 class="font-weight-bold" id="total">₽{{ price_total }}.00</h5>
                                        </li>
                                    </ul>
                                    <button type="submit" href="#" class="btn btn-dark rounded-pill py-2 btn-block">
                                        Оформить заказ
                                    </button>
                                </div>
                            </div>
                            <script>
                                const deliveryInput = $('#deliveryInput');
                                const deliveryOutput = $('#delivery-output');
                                deliveryInput.on('change', e => {
                                    const total = $('#total')[0];
                                    const price = $('#price')[0];
                                    const priceValue = Number(price.innerText.substring(1));
                                    if (Number(deliveryInput.val()) === 250) {
                                        deliveryOutput.removeClass('hidden');
                                        total.innerText = `₽${priceValue + 250}.00`;
                                    } else {
                                        deliveryOutput.addClass('hidden');
                                        total.innerText = `₽${priceValue}.00`;
}
                                });
                            </script>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

web/templates/web/comments.html
{% extends 'main.html' %}

    

    {% block content %}

    <h1 class="mt-4">Заявка: {{get_article.name}}</h1>

    <p><a href="/">Вернуться назад</a></p>





    <p>Дата создания:  {{get_article.create_date}}</p>

    <p>Название:  {{get_article.name}}</p>

    <p>Текст: {{get_article.text}}</p>
    <br>
    
    
    
    
    
    <p>Комментарии ({{get_article.comments_articles.all.count}})</p>
    
    
    <hr>
    
    
    
    
     {% if messages %}
    <div class="mt-4">
        <div class="alert alert-success">
            {% for m in messages %}
                {{m}}
            {% endfor %}
        </div>
    </div>
    {% endif %}
    
    <ul>
    {% for item in get_article.comments_articles.all %}
        <li>
        {{item.text}}<br>
        Дата создания: {{item.create_date}} <br>
        Оставил: {{item.author}} <br><br>
        
        </li>
    {% endfor %}
    </ul>
    
    
    
    
    


{% endblock %}

web/templates/web/index.html
{% extends 'web/main.html' %}
{% load static %}
{% block title_page %}
    <title>Главная страница</title>
{% endblock title_page %}
{% block content %}
    <section class="main-section paddind" id="Portfolio" style=""></section>

    <section class="main-section" id="service">
        <!--main-section-start-->
        <div class="container">
            <h2>Категории</h2>
            <h6>У нас большое разнообразие товаров</h6>
            <div class="row">
                <div class="col-lg-4 col-sm-6 wow fadeInLeft delay-05s">
                    <div class="service-list">
                        <div class="service-list-col1">
                            <i class="fa fa-paw"></i>
                        </div>
                        <div class="service-list-col2">
                            <h3>Листовые материалы</h3>

                        </div>
                    </div>
                    <div class="service-list">
                        <div class="service-list-col1">
                            <i class="fa fa-gear"></i>
                        </div>
                        <div class="service-list-col2">
                            <h3>Облицовочные материалы</h3>

                        </div>
                    </div>
                    <div class="service-list">
                        <div class="service-list-col1">
                            <i class="fa fa-apple"></i>
                        </div>
                        <div class="service-list-col2">
                            <h3>Изоляционные материалы</h3>

                        </div>
                    </div>
                    <div class="service-list">
                        <div class="service-list-col1">
                            <i class="fa fa-medkit"></i>
                        </div>
                        <div class="service-list-col2">
                            <h3>Сухие смеси и грунтовки</h3>

                        </div>
                    </div>
                </div>
                <figure class="col-lg-8 col-sm-6  text-right wow fadeInUp delay-02s">
                    <img src="{% static 'img/lerua.png' %}" alt="">
                </figure>

            </div>
        </div>
    </section>
    <!--main-section-end-->
    <section class="main-section alabaster"></section>
    <!--main-section alabaster-start-->
    <section class="main-section paddind" id="Portfolio" style="">
        <div class="container">
            <div class="row">
                <figure class="col-lg-5 col-sm-4 wow fadeInLeft">

                </figure>
                <div class="col-lg-7 col-sm-8 featured-work">
                    <h2>Наши плюсы</h2>

                    <div class="featured-box">
                        <div class="featured-box-col1 wow fadeInRight delay-02s">
                            <i class="fa fa-magic"></i>
                        </div>
                        <div class="featured-box-col2 wow fadeInRight delay-02s">
                            <h3>Высокое качество</h3>

                        </div>
                    </div>
                    <div class="featured-box">
                        <div class="featured-box-col1 wow fadeInRight delay-04s">
                            <i class="fa fa-gift"></i>
                        </div>
                        <div class="featured-box-col2 wow fadeInRight delay-04s">
                            <h3>Бонусы</h3>

                        </div>
                    </div>
                    <div class="featured-box">
                        <div class="featured-box-col1 wow fadeInRight delay-06s">
                            <i class="fa fa-dashboard"></i>
                        </div>
                        <div class="featured-box-col2 wow fadeInRight delay-06s">
                            <h3>Быстрая доставка</h3>

                        </div>
                    </div>
                    <a class="Learn-More" href="#">Learn More</a>
                </div>
            </div>
        </div>
    </section>

<section class="business-talking">
		<!--business-talking-start-->
		<div class="container">
			<h2> Комментарии клиентов.</h2>
		</div>
	</section>

        <section class="main-section paddind" id="Portfolio" style="">
        <style>
            .card-img-overlay {
                background-color: rgba(#000, 0.4);
            }

            .avatar {
                border: 0.1rem solid rgba(#fff, 0.3);
                max-width: 3rem;
            }

            @media (min-width: 0) {
                .g-mr-15 {
                    margin-right: 1.07143rem !important;
                }
            }

            @media (min-width: 0) {
                .g-mt-3 {
                    margin-top: 0.21429rem !important;
                }
            }

            .g-height-50 {
                height: 50px;
            }

            .g-width-50 {
                width: 50px !important;
            }
        </style>
        <div class="container">
            <div class="row">
                 {%  for comment in comments %}
                <div class="col-12 col-sm-8 col-md-6 col-lg-4">
                    <div class="card">
                        <img class="card-img"
                             src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/bologna-3.jpg"
                             alt="Bologna">
                        <div class="card-img-overlay text-white d-flex flex-column justify-content-center">
                            <blockquote class="blockquote text-right">
                                <p>"{{ comment.text }}"</p>
                            </blockquote>
                            <div class="author d-flex align-items-center">
                                <img class="avatar rounded-circle mx-2"
                                     src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/robert.jpg"
                                     alt="Bologna">
                                {{ comment.author }}
                            </div>
                        </div>
                    </div>
                </div>
                         {%  endfor %}
            </div>
        </div>
    </section>
     {% if user.is_authenticated %}
<div class="container">
		<section class="main-section contact" id="contact">

			<div class="row">
				<div class="col-lg-12 col-sm-5 wow fadeInUp delay-05s animated" style="visibility: visible; animation-name: fadeInUp;">
					<div class="form">
                        <h2 class="text-center mb-4">Оставьте комментария</h2>
						<div id="sendmessage">Your message has been sent. Thank you!</div>
						<div id="errormessage"></div>
						<form  class="comment-form" action="/" method="post" class="contactForm">
                                {% csrf_token %}
							<div class="form-group">
                                <input type="hidden" value="{{ user.id }}" name="author" id="id_author">
								<textarea class="form-control input-text text-area"
                                          name="text" rows="5" placeholder="Введите текста комментарии"></textarea>
							</div>
                             {% csrf_token %}
							<div class="text-center">
                                <button type="submit" class="input-btn">Отправить</button>
                            </div>
						</form>
					</div>
				</div>
			</div>
		</section>
	</div>
    {% endif %}
{% endblock content %}

web/templates/web/main.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  {% block title_page %}
  {% endblock %}
  {% load static %}
  <link rel="icon" href="{% static 'favicon.png' %}" type="image/png">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="img/x-icon">

  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css">
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
  <script type="text/javascript" src="{% static 'js/jquery.1.8.3.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-scrolltofixed.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.isotope.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/wow.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/classie.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/magnific-popup.js' %}"></script>
	<script src="{% static 'contactform/contactform.js' %}"></script>
</head>
<body>
  <nav class="main-nav-outer" id="test">
    <!--main-nav-start-->
    <div class="container">
      <ul class="main-nav">
        <li><a href="{% url 'reg' %}">Регистрация</a></li>
        <li><a href="{% url 'login' %}">Вход</a></li>
        <li><a href="{% url 'home' %}">Главная</a></li>
        <li><a href="{% url 'shop' %}">Магазин</a></li>
        <li><a href="{% url 'cart' %}">Корзина</a></li>
        <li><a href="{% url 'comments' %}">Отзывы</a></li>
      </ul>
      <a class="res-nav_click" href="#"><i class="fa fa-bars"></i></a>
    </div>
  </nav>
  {% if messages %}
    {% for mess in messages %}
      <div class="alert-success">
        {{ mess }}
      </div>
    {% endfor %}
  {% endif %}
  {% block content %}
  {% endblock content %}
  <script type="text/javascript">
    $(document).ready(function(e) {

      $('#test').scrollToFixed();
      $('.res-nav_click').click(function() {
        $('.main-nav').slideToggle();
        return false

      });

      $('.Portfolio-box').magnificPopup({
        delegate: 'a',
        type: 'image'
      });

    });
  </script>
  <script>
    wow = new WOW({
      animateClass: 'animated',
      offset: 100
    });
    wow.init();
  </script>
  <script type="text/javascript">
    $(window).load(function() {

      $('.main-nav li a, .servicelink').bind('click', function(event) {
        var $anchor = $(this);

        $('html, body').stop().animate({
          scrollTop: $($anchor.attr('href')).offset().top - 102
        }, 1500, 'easeInOutExpo');
        /*
        if you don't want to use the easing effects:
        $('html, body').stop().animate({
          scrollTop: $($anchor.attr('href')).offset().top
        }, 1000);
        */
        if ($(window).width() < 768) {
          $('.main-nav').hide();
        }
        event.preventDefault();
      });
    })
  </script>
  <script type="text/javascript">
    $(window).load(function() {
      var $container = $('.portfolioContainer'),
        $body = $('body'),
        colW = 375,
        columns = null;
      $container.isotope({
        // disable window resizing
        resizable: true,
        masonry: {
          columnWidth: colW
        }
      });
      $(window).smartresize(function() {
        // check if columns has changed
        var currentColumns = Math.floor(($body.width() - 30) / colW);
        if (currentColumns !== columns) {
          // set new column count
          columns = currentColumns;
          // apply width to container manually, then trigger relayout
          $container.width(columns * colW)
            .isotope('reLayout');
        }
      }).smartresize(); // trigger resize to set container width
      $('.portfolioFilter a').click(function() {
        $('.portfolioFilter .current').removeClass('current');
        $(this).addClass('current');
        var selector = $(this).attr('data-filter');
        $container.isotope({

          filter: selector,
        });
        return false;
      });
    });
  </script>
</body>
</html>